name: pinata
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
permissions:
  pull-requests: write
jobs:
  check_and_comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pinata
        uses: ./