name: pinata
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
permissions:
  pull-requests: write
jobs:
  update_pull_request_body:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pinata
        env:
          TZ: 'Asia/Tokyo' 
        uses: ./